### ISSUE TITLE
I wanna reproduce "fast subspace physics..." and try this repo results, if it is possiable to send me  related datasets?

### ISSUE THREAD

**Issue by DIOYF** [sutongkui/SubPhysics#3]
I would like to attempt to replicate the work on subspace physics, and I noticed that the repository provides relevant data. However, the git-lfs in the repository has expired. Is it still possible to obtain the dataset from the repository?

**Comment by sutongkui** [comment]
"the git-lfs in the repository has expired", I didn't understand. You mean the training data? or just the trained model?

**Comment by DIOYF** [comment]
when I using git clone or git lfs fetch directly in command will got this error response:

 "batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access."

I have solved this problem using this link method https://stackoverflow.com/questions/62905325/this-repository-is-over-its-data-quota-account-responsible-for-lfs-bandwidth-sh
